### PR TITLE
Add MSVC Compile changes

### PR DESCRIPTION
**Pull request by flok**
Add compatibility with the MSVC compiler (tested on VS 2019).

The change of order of the includes is intented as MSVC seems to have some problems with the <cmath> include not being at the top.
Also changed the cmake build script to differentiate between MSVC and other compilers. The option `BUILD_SHARED_LIBS` is used to build the shared lib on linux.

### CODE REVIEW

**Comment by grepthat** [comment]
Thanks for checking the compatibility with MSVC! I am only doing testing on Linux and MacOS. I just pushed a major refactor. Can you pull the changes and check again for compile errors?

**Comment by flok** [comment]
Added some missing thing but compiles fine!

**Comment by grepthat** [comment]
Thx for updating. Here some points from my side:
- Can you look into using `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`, as hinted [here]( https://stackoverflow.com/questions/33062728/cmake-link-shared-library-on-windows) to also build the library as `SHARED` library on Windows?
- Why is the include order change in _Math.hpp_ is necessary? I can't believe the standard headers are dependant on each other. Also asking because `format-files.sh` would re-arrange the includes again to be in alphabetical order.
- Is `<stdexcept>` in _Lane.h_ necessary? Lane.cpp does not throw/handle any exceptions.

**Comment by flok** [comment]
Just pushed some more things regarding your points. The restructure that you released yesterday fixed some error that i needed to work around for MSVC support

- cmake makes use of `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` now
- the `include <cmath>` doesn't need to be at the top of the file, but the `#define _USE_MATH_DEFINES` otherwise you will get undefined identifier for `M_PI` inside Arc.cpp, which includes the Math.hpp 
- Deleted the `<stdexcept>`, was needed before your restructure

**Pull request merged**
